version: "3.4"
services:
  db2:
    image: "ibmcom/db2:11.5.5.1"
    ports:
      - "50000:50000"
    environment:
      DB2INST1_PASSWORD: password
      DBNAME: bludb
      LICENSE: accept
      PERSISTENT_HOME: "false"
    privileged: true
